services:
  - name: vaultwarden
    type: web
    env: docker
    repo: ghcr.io/vaultwarden/server:latest
    plan: starter
    #httpPort: 80
    envVars:
      - key: DATABASE_URL
        value: mysql://vaultwarden:mysecretpassword@mysql:3306/vaultwarden

  - name: mysql
    type: web
    env: docker
    repo: docker.io/mariadb:latest
    plan: starter
    envVars:
      - key: MYSQL_DATABASE
        value: vaultwarden
      - key: MYSQL_USER
        value: vaultwarden
      - key: MYSQL_PASSWORD
        value: mysecretpassword

envVarGroups:
  - name: vaultwarden-env
    envVars:
      - key: DATABASE_URL
        value:
        fromService:
          name: mysql
          type: web
          property: env
          subproperty: MYSQL_DATABASE
      - key: MYSQL_USER
        value:
        fromService:
          name: mysql
          type: web
          property: env
          subproperty: MYSQL_USER
      - key: MYSQL_PASSWORD
        value:
        fromService:
          name: mysql
          type: web
          property: env
          subproperty: MYSQL_PASSWORD
