services:
  - name: vaultwarden
    type: web
    env: docker
    repo: vaultwarden/server:latest
    plan: starter
    port: 80
    envVars:
      - key: DATABASE_URL
        value: mysql://vaultwarden:mysecretpassword@mysql:3306/vaultwarden

  - name: mysql
    type: web
    env: docker
    repo: mariadb:latest
    plan: starter
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: mysecretpassword
      - key: MYSQL_DATABASE
        value: vaultwarden
      - key: MYSQL_USER
        value: vaultwarden
      - key: MYSQL_PASSWORD
        value: mysecretpassword

databases:
  - name: mysql
    type: mysql
    plan: starter
    version: latest
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        fromService:
          name: mysql
          type: web
          property: env
          subproperty: MYSQL_ROOT_PASSWORD
      - key: MYSQL_DATABASE
        fromService:
          name: mysql
          type: web
          property: env
          subproperty: MYSQL_DATABASE
      - key: MYSQL_USER
        fromService:
          name: mysql
          type: web
          property: env
          subproperty: MYSQL_USER
      - key: MYSQL_PASSWORD
        fromService:
          name: mysql
          type: web
          property: env
          subproperty: MYSQL_PASSWORD

    allowAccess:
      - service: vaultwarden
        property: env
        subproperty: DATABASE_URL
